### PR TITLE
Fix issue #40 and added new fileNameGenerator for slugged file

### PR DESCRIPTION
**Pull request by diegocavalletti**
Fix to https://github.com/Gargron/fileupload/issues/40 and added a new FileNameGenerator
that automatically slugify the file name so that on the server it appears with url friendly name

### CODE REVIEW

**Comment by adelowo** [comment]
The slug generator is great though. That should have been another pull request anyways.

**Comment by sirion89** [comment]
I think it mark the whole file because i have custom indentation in my dev-env, so when it reformatted the code it marked it all as modified, should i just delete the pull request and perform 2 new one? one with just the fix and the other one with the slug generator? 

Sorry but it's my first time doing this, i'll just follow your instructions

**Comment by diegocavalletti** [comment]
I think it mark the whole file because i have custom indentation in my dev-env, so when it reformatted the code it marked it all as modified, should i just delete the pull request and perform 2 new one? one with just the fix and the other one with the slug generator?

Sorry but it's my first time doing this, i'll just follow your instructions

**Comment by adelowo** [comment]
@diegocavalletti That would be better. 2 pull requests would be better.

**Pull request closed without merging**
