### PR TITLE
Another docs improvement

### PR DESCRIPTION
**Pull request by radmax**
- added few forgotten things in #39

### CODE REVIEW

**Comment by radmax** [comment]
I commited another batch of improvedments for readme. Hopefully not much more is needed. 😉

**Comment by adelowo** [comment]
Thanks.. what are your thoughts as per #36 though  - i am asking because of the short array syntax you introduced in the docs and the library supports `5.3` ?

**Comment by radmax** [comment]
PHP 5.3 still has high usage. I think that library can still support 5.3 for near future, but i should add note, that docs are for PHP 5.4+.

**Comment by adelowo** [comment]
I don't think notes are necessary.. ___as that can be figured out by the developer ?___

**Pull request merged**
