### PR TITLE
PHP 8 Compatibility

### PR DESCRIPTION
**Pull request by netsnatch**
Breaking change
Require PHP7.2+

### CODE REVIEW

**Comment by adelowo** [comment]
Thanks a lot @netsnatch . Apologies for the late response

**Comment by netsnatch** [comment]
@adelowo 
Thanks. Are you going to create a new release or will it be done later?

**Comment by adelowo** [comment]
@netsnatch i will create a new release this weekend.

**Comment by mk-wieland** [comment]
@adelowo is this gonna get tagged soon?

**Pull request merged**
